"""Phase 03 typed LLM gateway exports."""

from nullvector.llm.errors import (
    GatewayAuthError,
    GatewayConfigurationError,
    GatewayContextLengthError,
    GatewayError,
    GatewayNetworkError,
    GatewayProviderRefusalError,
    GatewayRateLimitError,
    GatewayTimeoutError,
    GatewayUnknownProviderError,
    GatewayUnsupportedCapabilityError,
    GatewayValidationError,
)
from nullvector.llm.multimodal_gateway import (
    MultimodalFailureCategory,
    MultimodalGatewayConfig,
    MultimodalGatewayError,
    MultimodalGatewayRequest,
    MultimodalGatewayService,
    MultimodalProviderConfig,
    NoopMultimodalProviderAdapter,
    NoopMultimodalResponse,
    RegionImageInput,
    VisualEnrichmentService,
    VisualInsightResponse,
)
from nullvector.llm.protocols import RedactionHook, StructuredLLMGateway
from nullvector.llm.providers import (
    LiteLLMSDKAdapter,
    NoopProviderAdapter,
    NoopScriptedResponse,
    OpenAIResponsesHTTPAdapter,
)
from nullvector.llm.service import GatewayRepairEngine, GatewayService
from nullvector.llm.types import (
    GatewayAssuranceMode,
    GatewayAttempt,
    GatewayAuditConfig,
    GatewayAuditRecord,
    GatewayConfig,
    GatewayFailure,
    GatewayFailureCategory,
    GatewayRequest,
    GatewayRetryPolicy,
    GatewaySuccess,
    GatewayUsage,
    LiteLLMProviderConfig,
    LLMMessage,
    LLMRole,
    OpenAIProviderConfig,
    StructuredOutputMode,
)

__all__ = [
    "GatewayAssuranceMode",
    "GatewayAttempt",
    "GatewayAuditConfig",
    "GatewayAuditRecord",
    "GatewayAuthError",
    "GatewayConfig",
    "GatewayConfigurationError",
    "GatewayContextLengthError",
    "GatewayError",
    "GatewayFailure",
    "GatewayFailureCategory",
    "GatewayNetworkError",
    "GatewayProviderRefusalError",
    "GatewayRateLimitError",
    "GatewayRepairEngine",
    "GatewayRequest",
    "GatewayRetryPolicy",
    "GatewayService",
    "GatewaySuccess",
    "GatewayTimeoutError",
    "GatewayUnknownProviderError",
    "GatewayUnsupportedCapabilityError",
    "GatewayUsage",
    "GatewayValidationError",
    "LLMMessage",
    "LLMRole",
    "LiteLLMProviderConfig",
    "LiteLLMSDKAdapter",
    "MultimodalFailureCategory",
    "MultimodalGatewayConfig",
    "MultimodalGatewayError",
    "MultimodalGatewayRequest",
    "MultimodalGatewayService",
    "MultimodalProviderConfig",
    "NoopMultimodalProviderAdapter",
    "NoopMultimodalResponse",
    "NoopProviderAdapter",
    "NoopScriptedResponse",
    "OpenAIProviderConfig",
    "OpenAIResponsesHTTPAdapter",
    "RedactionHook",
    "RegionImageInput",
    "StructuredLLMGateway",
    "StructuredOutputMode",
    "VisualEnrichmentService",
    "VisualInsightResponse",
]
