"""Project-wide constants."""

EXPECTED_PYMUPDF_VERSION = "1.27.2"
EXPECTED_PYPDF_VERSION = "6.8.0"
VERSION_POLICY = "strict_runtime_lockstep"
CERTIFIED_PYMUPDF_VERSIONS = (EXPECTED_PYMUPDF_VERSION,)
CERTIFIED_PYPDF_VERSIONS = (EXPECTED_PYPDF_VERSION,)
DEFAULT_ARTIFACT_ROOT = "artifacts/parse_runs"
DEFAULT_ACQUISITION_ARTIFACT_ROOT = "artifacts/acquisition_runs"
