"""Shared deterministic thresholds used across tree heuristics."""

from __future__ import annotations

TITLE_TOKEN_CONTAINMENT_THRESHOLD = 0.60
SHORT_TITLE_MAX_LENGTH_FOR_EDIT_DISTANCE = 32
SHORT_TITLE_EDIT_DISTANCE_THRESHOLD = 2
MAXIMUM_ALLOWED_PAGE_ADJACENCY = 1
REPEATED_HEADER_FOOTER_MIN_REPETITIONS = 2
TOP_OF_PAGE_LINE_LIMIT = 3

__all__ = [
    "MAXIMUM_ALLOWED_PAGE_ADJACENCY",
    "REPEATED_HEADER_FOOTER_MIN_REPETITIONS",
    "SHORT_TITLE_EDIT_DISTANCE_THRESHOLD",
    "SHORT_TITLE_MAX_LENGTH_FOR_EDIT_DISTANCE",
    "TITLE_TOKEN_CONTAINMENT_THRESHOLD",
    "TOP_OF_PAGE_LINE_LIMIT",
]
